### DISCUSSION TITLE
Entity with alarm bell status

### DISCUSSION THREAD

**Discussion by proasnet** [ParadoxAlarmInterface/pai#418] [General]
Hi, I have installed PAI in HA (HASOS), EVOHD and IP150.
I can not found way for status of a bell, actived alarm bell in armed zone.
In MQTT explorer, are PGM outs, but not a bell. EVOHD has a bell output.
I have this in a configuration.yaml
```
binary_sensor:
  - name: Paradox 1NP Alarm
    unique_id: paradox_1np_alarm
    state_topic: "paradox/states/partitions/Podlazie_1NP/audible_alarm"
    payload_on: "True"
    payload_off: "False"
    availability:
      - topic: "paradox/interface/availability"
        payload_available: "online"
        payload_not_available: "offline"
```
But it not working.
Help me with this please.
