### ISSUE TITLE
All Partition - HA feature

### ISSUE THREAD

**Issue by b0c1** [ParadoxAlarmInterface/pai#132]
Currently, HA auto-discovery only support by partition state and control. 
But the MQTT interface can control all partition at once when the partition name is "all".

## Feature description
Here is my old "All partition" emulated mqtt control panel definition:
```yaml
alarm_control_panel:
  - platform: mqtt
    name: Full
    state_topic: 'paradox/states/partitions//current_state'
    command_topic: 'paradox/control/partitions/all'
    availability_topic: 'paradox/interface/availability'
    payload_disarm: 'disarm'
    payload_arm_home: 'arm_stay'
    payload_arm_away: 'arm'
    payload_arm_night: 'arm_sleep'
```
Maybe same can be published to the auto-discovery (the state_topic maybe aggregated from all partition to a `paradox/states/partitions/all`)

**Comment by cybertza** [comment]
If all fails you can always use Node-Red to emulate the same thing.
if that is a requirement for you.
For me arming all the partitions at the same time defeats the purpose of having them, 
the bottom of my yardi used to arm much earlier than the top, i eventually just changed my setup to home/sleep and all the outside sensors i changed to a different alarm tone.
 i can however understand the requirement for disarming them at the same time, i used to use node for that.

**Comment by yozik04** [comment]
Just use a custom `alarm_control_panel` without mqtt. Use templates and rules. Documentation about it is "great"! https://www.home-assistant.io/integrations/alarm_control_panel/

**Comment by yozik04** [comment]
I do not like an idea arming/disarming all. I have 5 partitions at my place. 3 of them are constantly armed and should not be disarmed.

**Comment by yozik04** [comment]
Anybody managed to make it work with scripts and separate alarm_control_panel ?

**Comment by cybertza** [comment]
Use node red.

**Comment by yozik04** [comment]
Try to modify and use that:
https://www.home-assistant.io/integrations/cover.template/#multiple-covers

**Comment by yozik04** [comment]
https://www.home-assistant.io/integrations/alarm_control_panel.template/

**Comment by yozik04** [comment]
```yaml
# Example configuration.yaml entry
alarm_control_panel:
  - platform: template
    panels:
      home_alarm_panel:
        value_template: "{{ states('alarm_control_panel.first_floor') }}"
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          data:
            entity_id:
              - alarm_control_panel.first_floor
              - alarm_control_panel.second_floor
        arm_home:
          service: alarm_control_panel.alarm_arm_home
          data:
            entity_id:
              - alarm_control_panel.first_floor
              - alarm_control_panel.second_floor
        disarm:
          service: alarm_control_panel.disarm
          data:
            entity_id:
              - alarm_control_panel.first_floor
              - alarm_control_panel.second_floor
```

This should work. Not tested.
