### ISSUE TITLE
User Name that Arm/Disarm the system

### ISSUE THREAD

**Issue by cdk222** [ParadoxAlarmInterface/pai#160]
MG5050
HomeAssistant

Im not sure if this is possible given the sheer volume of events in the 'Events -- Raw' topic; however has anybody tried to isolate the events that deal with Arming and Disarming the system so that we can isolate the Username of the person who last Arm/Disarm with a timestamp.

I was able to capture the events using MQTT Explorer; however Im not sure how to isolate the information I need from those......or if even if it is possible within the Homeassistant Pai addon

**Comment by jpbarraca** [comment]
ARM:
```{"additional_data": {}, "change": {}, "id": 5, "key": "user,USERNAME,", "label": "USERNAME", "label_type": null, "level": "INFO", "major": 29, "message": "Arming by user USERNAME", "minor": 5, "module": "0xe", "name": "USERNAME", "partition": 1, "tags": ["arm"], "timestamp": "2020-10-11T11:27:00", "type": "user"}
```

DISARM:
```{"additional_data": {}, "change": {}, "id": 5, "key": "user,USERNAME,", "label": "USERNAME", "label_type": null, "level": "INFO", "major": 31, "message": "Disarming by user USERNAME", "minor": 5, "module": "0xe", "name": "USERNAME", "partition": 1, "tags": ["disarm"], "timestamp": "2020-10-11T11:27:00", "type": "user"}```

However, because the events are not exposed as homeassistant entities, I'm not sure you can easily create a template sensor to extract these values. I would start with exposing the Sensor and then look at building the template.

**Comment by rjcds** [comment]
> I was able to capture the events using MQTT Explorer;

What are you editing in the config to get this ?

I've tried uncommenting MQTT_PUBLISH_RAW_EVENTS = True
but I'm not seeing anything in MQTT Explorer in paradox/events/raw other than the panel time and date...

**Comment by jpbarraca** [comment]
Yes. You should get events when zones open or when a partition is armed/disarmed

**Comment by rjcds** [comment]
> Yes. You should get events when zones open or when a partition is armed/disarmed

Just seeing panel date/time in paradox/events/raw

What needs to be enabled in the config to get all the other events ?

**Comment by jpbarraca** [comment]
Can you increase the log level to DEBUG including packet and message dumps? Then activate some zones or arm/disarm the panel and see if there are events coming from the panel. If you prefer, send the log to my email.

**Comment by rjcds** [comment]
Thanks @jpbarraca I've emailed you the log. There are a few errors relating to 'Could not create event from change'...

**Comment by jpbarraca** [comment]
You can safely ignore that message as it is a bit misleading.
Regarding the log you sent, the normal set of messages is there, including messages such as the following. XXXX is the partition and YYYYY the user. Some other fields are redacted.

```
paradox/events/raw={"additional_data": {}, "change": {"arm": true}, "id": 1, "key": "partition,XXXXX,arm=True", "label": "XXXXX", "label_type": "b'\\x01'", "level": "INFO", "major": 9, "message": "Arming XXXXX with YYYYYY .......", "minor": 1, "minor2": 0, , "name": "XXXXXX", "partition": 1, "tags": ["arm"], .... , "type": "partition"}
```

**Comment by rjcds** [comment]
Thanks so much @jpbarraca 

Here's the automation that's working for me so far:

```yaml
- alias: ArmedBy
  trigger:
    platform: mqtt
    topic: 'paradox/events/raw'
  condition:
    condition: template
    value_template: >
      {{ trigger.payload_json['change']['arm'] == True or
         trigger.payload_json['change']['arm'] == False }}
  action:
    service: notify.pushover
    data:
      message: >
        {% if trigger.payload_json['change']['arm'] == True -%}
          House armed by {{ trigger.payload_json['message'][17:-12] }}
        {%- else -%}
          House disarmed by {{ trigger.payload_json['message'][17:-12] }}
        {%- endif %}
```
