### ISSUE TITLE
Trigger alarm via mqtt in new firmwares.

### ISSUE THREAD

**Issue by yozik04** [ParadoxAlarmInterface/pai#162]
## Feature description

- EVO192 supports alarm triggering in versions 7.15+
- SP/MG supports alarm triggering in versions 7.10+

Implement an MQTT endpoint to send a message to alarm.

**Comment by yozik04** [comment]
I have pushed https://github.com/ParadoxAlarmInterface/pai/tree/send_panic branch to verify the code.

MQTT topic format: `paradox/panic/{panic_type}/{partition}`
Payload: `{user_id}`

Replace data in curly brackets.

`panic_type` can be:
- emergency
- medical
- fire

`user_id` and `partition`: numeric id or label

**Comment by yozik04** [comment]
That will fail. I need full debug output what was received from the panel after this command.

**Comment by DjBac** [comment]
Are there any updates on this topic? It would be a great function of psi. At the moment I can trigger the alarm with an esp32 relay used as a zone, but triggering it through mqtt would be awesome!

**Comment by yozik04** [comment]
Nope, unfortunately.

**Comment by DjBac** [comment]
Thank you!

**Comment by gytisgreitai** [comment]
@DjBac can you show ho you have wired the esp32 ?

**Comment by philip-sterne** [comment]
I have some spare time coming up. If someone can point me in the direction of what needs to be done then I will gladly code it up. 

(This would be a great feature that I would use a lot!)

**Comment by fishermanG** [comment]
Hi everyone. Below are my configs. 

Using esphome to interface between paradox alarm and HA and to trigger one of the zone 'remotely' when armed (essentially like a panic button). 

### Equipments:

1. Paradox SP5500
2. USB Buck DC-DC Converter 12v-5v (I powered using USB cable but you could wire up the output of the buck converter directly to VIN and GND)
3. ESP8266
4. 1 channel 5v/3.3v Relay Module

![Fritzing_bb](https://user-images.githubusercontent.com/24431798/135411875-487e2682-08b4-46db-a6df-eac59bdb2f83.jpg)


### ESPHome Config:
```
esphome:
  name: esp-paradox-alarm
  platform: ESP8266
  board: nodemcuv2

logger:
  baud_rate: 0

api:

ota:
  password: "xxx"

wifi:
  ssid: "WIFI_SSID"
  password: "secret_ssid"
external_components:
  - source: github://oxan/esphome-stream-server

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3
  stop_bits: 1

stream_server:
  uart_id: uart_bus
  port: 23
  
sensor:
  - platform: uptime
    name: Uptime Sensor
    
switch:
  - platform: gpio
    pin: GPIO5 #D5
    inverted: false
    id: relay
    name: "Alarm Trigger"
    icon: "mdi:alarm"
    on_turn_on:
    - delay: 1200ms
    - switch.turn_off: relay

```
Hope this helps.
