### ISSUE TITLE
Generate HA switches to "clear alarm memory" for zones

### ISSUE THREAD

**Issue by clau-bucur** [ParadoxAlarmInterface/pai#171]
I see that for HA switches to bypass the zones are auto generated (eg. zone_Name_bypass).
Would it be possible to auto generate "clear alarm memory" switches also ?

**Comment by jpbarraca** [comment]
Probably it's possible but we do not know how to do it. Needs investigation

**Comment by clau-bucur** [comment]
I'd say similar to bypass switches. Here's a "clear alarm memory" switch I have created:
`switch:
  - platform: mqtt
    name: Zone Atelier Clean Alarm Memory
    command_topic: paradox/control/zones/Atelier
    payload_off: clear_alarm_memory
    state_topic: paradox/states/zones/Atelier/generated_alarm
    state_on: true
    state_off: false
`

**Comment by clau-bucur** [comment]
Similarly, the keyswitch triggered sensors are missing from auto-generation:
```
binary_sensor:
  - platform: mqtt
    state_topic: paradox/states/key-switch/1/triggered
    name: Paradox Keyswitch Pod
    payload_on: true
    payload_off: false
```
