### ISSUE TITLE
Time init failure after 2.2.5

### ISSUE THREAD

**Issue by ipetrovits** [ParadoxAlarmInterface/pai#203]
## Alarm system
- SP6000
- IP150

## Environment
- RaspberryPI 4
- Docker
- Mosquitto
- HA on Docker

## Git branch
:latest at docker hub

## Describe the bug
PAI is not working with this release, producing time sync errors

## To Reproduce
Use the below tags for docker image:
:latest
:2.3.0
:dev-latest

## Workaround
Hardcode the below tag to docker image:
:2.2.5

## Logs
Terminal and file logging set to DEBUG.

Terminal:
This repeats
```
Current thread 0xb6f66390 (most recent call first):,
Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time,
PermissionError: [Errno 1] Operation not permitted
```

File:
_no log being generated even with DEBUG set_

**Comment by yozik04** [comment]
Hi. How you installed PAI?

**Comment by ipetrovits** [comment]
> Hi. How you installed PAI?

Hi, via Docker image, compose file:

```
version: "3"
services:
  pai:
    container_name: pai
    image: paradoxalarminterface/pai:2.2.5
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/pai/config:/etc/pai:ro
      - /opt/pai/log:/var/log/pai
      - /opt/pai/data:/data
```
Config holds a tailored pai.conf, data maybe totally unneccesary, i don't remember why i made that.. its there since may, 2020.
