### ISSUE TITLE
New notification in HA “The add-on … uses secrets which are detected as not secure”.

### ISSUE THREAD

**Issue by woody4165** [ParadoxAlarmInterface/pai#217]
Hi

with new HA upgrades I started receiving a persistent notification regarding the use of non-secure password in the PAI addon.

I've checked the `MQTT_PASSWORD` and the `IP_INTERFACE_PASSWORD`, but they are fine.
The one that is most probably causing this notification is `PASSWORD: '0000'`

In any case, even if I change to any value, since it's a 4 number password will be surely identified as insecure.

Probably changing the field name will not be seen as a password.

Anyone else getting this notification?

Thanks

**Comment by salvadofamily** [comment]
Same here.

**Comment by yozik04** [comment]
I do not want to start a fight with just a message.

**Comment by woody4165** [comment]
Sorry, I don't understand your comment...

In any case, actually I've removed the annoying persistent notification with this automation I found on the HA community, but it's just a workaround and it removes ALL the notifications for insecure passwords.

```
- id: persistent_notification_clear_pwned
  alias: persistent_notification_clear_pwned
  mode: parallel
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: create
  condition:
  - condition: template
    value_template: '{{ ''supervisor_issue_pwned'' in trigger.event.data.service_data.notification_id
      }}
```
