### ISSUE TITLE
PUSHOVER_BROADCAST_KEYS is not configurable in HA

### ISSUE THREAD

**Issue by yozik04** [ParadoxAlarmInterface/pai#218]
With latest version of HomeAssistant it is not possible to configure PUSHOVER_BROADCAST_KEYS anymore.

I have to change configuration format to support supervisor configuration schema limitations.

New format will be:
```python
"PUSHOVER_BROADCAST_KEYS": [  # Pushover user or group keys to broadcast notifications to
  {
    'user_key':'<user_key>',
    'devices': '*'  # value can be '*' or comma separated list of device names
  }                
],
```

In YAML:
```yaml
PUSHOVER_BROADCAST_KEYS:
  - user_key: "<user_key>"
    devices: "*"
```
