### ISSUE TITLE
Paradox with google assistant

### ISSUE THREAD

**Issue by n00bster-za** [ParadoxAlarmInterface/pai#297]
Been running the PAI addon for a long time and working well. I am now trying to get it working with Google assistant. I have already done the HA and Google integration and I have exposed the Alarm panel entities to Google Home. But I cant seem to activate them using voice and also don't know how will I tell google to activate sleep mode or away mode for the alarm. 

Please help. 

```
project_id: xxx
secure_devices_pin: xxx
service_account:
  private_key: "-----BEGIN PRIVATE KEY-----"
  client_email: xxx
report_state: true
expose_by_default: true
exposed_domains:
  - switch


entity_config: 
  alarm_control_panel.house:
      name: House Alarm
      expose: true
      room: House
  alarm_control_panel.beams:
      name: Beams
      expose: true
      room: House
```
