### ISSUE TITLE
I can't start it on Raspberry Pi4 + Docker

### ISSUE THREAD

**Issue by lpaolini** [ParadoxAlarmInterface/pai#330]
## Alarm system
No alarm panel connected

## Environment
Raspberry Pi4 running Raspberry Pi OS 11.5, Docker v. 20.10.21

### Git branch
dev

## Question
I can't start it using docker compose up (see error in the logs).
Am I doing anything wrong? 

### pai.conf
```
CONNECTION_TYPE: Serial
SERIAL_PORT: '/dev/ttyUSB0'
SERIAL_BAUD: 9600
```
### Docker-compose.yml
```
version: '3'

services:
  pai:
    container_name: pai
    restart: unless-stopped
    image: paradoxalarminterface/pai:latest
    volumes:
      - "~/docker/pai/config:/etc/pai:ro"
      - "~/docker/pai/log:/var/log/pai:rw"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - TZ=EUROPE/Tallinn
    user: "1000:1000"
    devices:
      - "/dev/ttyUSB0"
    ports:
      - "10000:10000"
```
## Logs
```
pai  | Attempting to load configuration from /etc/pai/pai.conf
pai  | Traceback (most recent call last):
pai  |   File "/usr/local/bin/pai-service", line 8, in <module>
pai  |     sys.exit(main())
pai  |   File "/usr/local/lib/python3.9/site-packages/paradox/console_scripts/pai_run.py", line 36, in main
pai  |     main(args)
pai  |   File "/usr/local/lib/python3.9/site-packages/paradox/main.py", line 120, in main
pai  |     cfg.load()
pai  |   File "/usr/local/lib/python3.9/site-packages/paradox/config.py", line 300, in load
pai  |     entries = self._read_config()
pai  |   File "/usr/local/lib/python3.9/site-packages/paradox/config.py", line 372, in _read_config
pai  |     exec(f.read(), None, entries)
pai  |   File "<string>", line 2, in <module>
pai  | NameError: name 'Serial' is not defined
pai exited with code 1
```
