### ISSUE TITLE
Alarm Triggered by what Zone Notify 

### ISSUE THREAD

**Issue by FigJam23** [ParadoxAlarmInterface/pai#344]
Is there a easy way to get the triggered by what Zones when armed.  I get armed disarmed triggered via the Pai alarm Panel but it would be nice if the alarm panel integration could show what Zone or zones have been triggered while armed and push them to notify mobile app

**Comment by somejavadev** [comment]
@FigJam23 are you by any chance using the home assistant integration? I have done this via an automation in Home Assistant.

Adding it below if anyone is interested.

Create an input text helper:  `input_text.last_zone_in_alarm`

```yaml
alias: Paradox Zone In Alarm
description: ""
trigger:
  - platform: mqtt
    topic: paradox/states/zones/+/generated_alarm
    payload: "True"
condition: []
action:
  - service: input_text.set_value
    data:
      value: >-
        Zone: {{ trigger.topic | regex_replace(find='paradox/states/zones/',
        replace='', ignorecase=True) | regex_replace(find='/.*', replace='',
        ignorecase=True)| regex_replace(find='_', replace=' ', ignorecase=True)
        | lower}}
    target:
      entity_id: input_text.last_zone_in_alarm
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: notify.notify
    data:
      title: Alarm
      message: The alarm went of in {{ states('input_text.last_zone_in_alarm') }}
mode: single
```
