### ISSUE TITLE
Correct method for bypassing zones

### ISSUE THREAD

**Issue by reflexsa** [ParadoxAlarmInterface/pai#475]
Firstly, thanks for this integration. Has been a blessing!
I wanted to ask something regarding bypassing zones. The way I have been bypassing my zones (as needed) through home assistant was using the following in my configuration.yaml:
```
#Alarm bypass zones
mqtt:
  switch:
    - name: "Guest bedroom bypass"
      command_topic: "paradox/control/zones/Guest_bedroom"
      state_topic: "paradox/states/zones/Guest_bedroom/bypassed"
      state_on: "True"
      state_off: "False"
      payload_on: "bypass"
      payload_off: "clear_bypass"
```
This seems to work before and after arming which is convenient, but I noticed the 'attached image' in Babyware, I'm not sure if it is actually a problem or if it is caused by how I am bypassing.
![bypass](https://github.com/ParadoxAlarmInterface/pai/assets/82560444/5815d1b4-06c8-431b-85a6-e330cd129bb1)

After doing a bit of reading here I assume the preferred way is using `bypassed` in `HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES`, however I am not sure how to see or access these properties. After adding `bypassed` to in the configuration I only see entities for the 'open' and 'tamper', but not 'bypassed'
